name = "steady-study-web"
compatibility_date = "2026-02-22"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "VOIDRUSH_DB"
database_name = "steady_study_voidrush_prod"
database_id = "d3fed7be-f7ad-4e34-812a-f3107d0dc408"
preview_database_id = "b18866a7-f8b2-43dd-8196-5aa013903471"

[[analytics_engine_datasets]]
binding = "VOIDRUSH_ANALYTICS"
dataset = "voidrush_events"
